package ReverseModule;


/**
* ReverseModule/ReverseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ReverseModule.idl
* Tuesday, 21 April, 2020 3:28:28 AM IST
*/

public interface ReverseOperations 
{
  String reverse_string (String str);
} // interface ReverseOperations
